### ISSUE TITLE
Elixir 1.5 - error compiling

### ISSUE THREAD

**Issue by jasongoodwin** [zovafit/timex_poison#1]
Hey this doesn't seem to work in my project (poison 2, elixir 1.5).
I'm not very experienced with macros so...
Error during compilation
```
== Compilation error in file lib/command/my_command.ex ==
** (SyntaxError) lib/command/my_command.ex:2: syntax error before: 'keys':
    (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

Struct:
```
defmodule Command.MyCommand do
  use TimexPoison keys: [:production_date, :start_time, :end_time, :timestamp]

  defstruct 
            production_date: nil,
            start_time: nil,
            end_time: nil,
            timestamp: nil
end

```

**Comment by jasongoodwin** [comment]
I just needed a comma before keys! I'll try to make a pr for this.
